# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: crud
  password: crud

development:
  <<: *default
  database: crud_api_development

test:
  <<: *default
  database: crud_api_test

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: crud_api_production