# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c04aa698e95a2b90bb156e6032e01d5f149d4d55874b8ec516ad05b377f68e413ce0c6e8827c42aa8fd6eb5b1585f362b552ae4a243198b70d8edd9e3a2d7eb5

test:
  secret_key_base: c491e8c894a110cf402526058c01c7987cd619b3131746fdaf002961f99871df178be95e2fd2367772f8231df25f6f63c481f5ef6e8847d20621bd147514d1b3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
